import { useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const TermsAndConditions = () => {
  useEffect(() => {
    document.title = 'Terms and Conditions - Vanshu Agarwal';
    
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', 'Terms and Conditions for using Vanshu Bot and Vanshu Agarwal\'s portfolio website. Read about data usage, privacy, and service terms.');
    }
  }, []);

  return (
    <main className="min-h-screen pt-24 pb-16 bg-background" role="main">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="animate-fade-in">
          <header className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-primary via-primary-glow to-primary bg-clip-text text-transparent">
              Terms and Conditions
            </h1>
            <p className="text-muted-foreground text-lg">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </header>

          <div className="space-y-6 animate-slide-up">
            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">1. Acceptance of Terms</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  By accessing and using this website and Vanshu Bot, you accept and agree to be bound by the terms and provision of this agreement. 
                  If you do not agree to abide by the above, please do not use this service.
                </p>
              </CardContent>
            </Card>

            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">2. Use of Vanshu Bot</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  Vanshu Bot is an AI-powered chatbot designed to provide information about Vanshu Agarwal's work, skills, and projects. 
                  The bot uses AI technology powered by Lovable AI and Gemini models.
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>The bot's responses are generated by AI and may not always be 100% accurate</li>
                  <li>Conversations are processed in real-time and are not stored permanently</li>
                  <li>The service is provided free of charge</li>
                  <li>We reserve the right to limit usage in case of abuse</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">3. Data Privacy</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  We respect your privacy and are committed to protecting your personal information:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Chat conversations are processed through secure AI endpoints</li>
                  <li>We do not store personal information without consent</li>
                  <li>Session data is temporary and automatically cleared</li>
                  <li>We use cookies only for essential functionality</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">4. Intellectual Property</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  All content on this website, including text, images, videos, and code, is the property of Vanshu Agarwal unless otherwise stated. 
                  Unauthorized reproduction or distribution is prohibited.
                </p>
              </CardContent>
            </Card>

            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">5. Limitation of Liability</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  This service is provided "as is" without any warranties. We shall not be liable for any damages arising from the use of this website or Vanshu Bot, 
                  including but not limited to direct, indirect, incidental, or consequential damages.
                </p>
              </CardContent>
            </Card>

            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">6. Changes to Terms</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms. 
                  We recommend reviewing this page periodically.
                </p>
              </CardContent>
            </Card>

            <Card className="card-gradient border-border hover:border-primary/50 transition-smooth">
              <CardHeader>
                <CardTitle className="text-2xl text-primary">7. Contact Information</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground space-y-4">
                <p>
                  If you have any questions about these Terms and Conditions, please contact us through the contact page or email at nextupstudioyt@gmail.com
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </main>
  );
};

export default TermsAndConditions;
